apiVersion: v1
kind: Service
metadata:
  namespace: k8s-module2
  name: post-service
spec:
  type: LoadBalancer
  selector:
    app: post-service-pod
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-module2
  name: post-service-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service-pod
  template:
    metadata:
      labels:
        app: post-service-pod
    spec:
      containers:
        - name: post-service
          image: com.epam/post-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: PROFILE
              valueFrom:
                configMapKeyRef:
                  name: app-config-map
                  key: profile
            - name: SERVICE_NAME
              value: user-database-service
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: postDb
                  name: db-secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: db-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-secret
